### ISSUE TITLE
JSON data type

### ISSUE THREAD

**Issue by DaAwesomeP** [marianr/seneca-postgres-store#17]
Does this adapter support the new Postgre JSON data type and searching with it? It allows Postgre to be used effectively as a document store.

**Comment by mirceaalexandru** [comment]
Hi @DaAwesomeP 

No, it is not supported. 
It is also not our intention to have support for this soon as we want to have all Seneca stores supporting a common API and this feature is not part of that.

You can get the native connection object by calling native$ and then use the features that pg is offering.

I think I may close this, if you want want to add comments please open it again.
