### ISSUE TITLE
how can I specify the db schema when creating an entity?

### ISSUE THREAD

**Issue by viczam** [marianr/seneca-postgres-store#18]

**Comment by mirceaalexandru** [comment]
@viczam please take a look here:

http://senecajs.org/tutorials/understanding-data-entities.html

There you can see explanations about using multiple zones for your entities. 

Let me know if it is OK by closing this, or add a comment.

**Comment by viczam** [comment]
uhm, not really.. I don't want to specify a zone, but a postgresql schema, as a I have my tables nested under a schema.

When parsing the canon, seneca accepts only words for zone / base / name, but you can schema a name like this:
```js
seneca.make({
  entity$: {
    name: `${schema}.${table}`
  }
}).canon$({array: true})
```
But the table name is escaped later on, so that won't work either.

**Comment by viczam** [comment]
is there a way to specify a connection string when setting up the seneca plugin, instead of the existing object?

**Comment by mirceaalexandru** [comment]
You can specify also default schema for user:

ALTER USER user_name SET search_path to 'schema';

or when using multiple schema:

SET search_path TO myschema,public;

**Comment by mirceaalexandru** [comment]
You can specify a connection string of the form:

postgres://username:password@localhost/database

**Comment by mirceaalexandru** [comment]
I think this is a candidate for new feature, specify schema in connect object/url. I will open a feature issue.

**Comment by viczam** [comment]
how can I specify the connection string when setting up the plugin?

Probably I wasn't clear enough, but my issue is that I have a lot of tables nested under a schema and I want to make seneca entities for some of those tables and I can't find a way to do that. And that's because when calling `saneca.make('SomeEntityThatCorrespondsToATable')`, it doesn't know it has to prefix the table with the schema name

**Comment by mirceaalexandru** [comment]
Yes, for now there is not implemented the feature you need - first I misunderstood what you need. You can use a workaround like the one I described in my previous comment above for now by setting the default schema for connected user. In this case you do not need to use qualified table name.

I created a issue for this feature it will be added on next version.

**Comment by viczam** [comment]
A potential fix would be not to escape the table name in query_builder.js, or use a different strategy to allow schema definition as well.
If you do that, you can specify the entity definition this way:
```js
seneca.make$({
  entity$: {
    name: `"${schema}"."${table}"`,
  }
});
```

**Comment by mirceaalexandru** [comment]
To match the Seneca store API and not add that "dot naming" that is not standard for us I think the best approach is to specify the schema in the connection object. Then you can use zones/base to select schema as usual for all stores.

I will take a look on that.

**Comment by viczam** [comment]
Sounds good, although you might have multiple schemas under the same database and you'll be forced to create different connections to the same database to target each schema in particular.

**Comment by mirceaalexandru** [comment]
Yes, but this is the way Seneca stores are used to manage
tables/collections from different locations. It allows you to move very
easy schemes to a different database/machine or even different db engine.

malex
Pe 07.01.2016 17:53, "Victor Zamfir" <notifications@github.com> a scris:

**Comment by viczam** [comment]
Good point. Then allowing defining schema through the connection sounds like the best solutions.

**Comment by mirceaalexandru** [comment]
@viczam I will let you know when this feature is published

**Comment by brycereynolds** [comment]
Did this feature ever ship?
