### ISSUE TITLE
UUID awareness and overriding the entity.id$

### ISSUE THREAD

**Issue by combsco** [marianr/seneca-postgres-store#6]
Please add to the readme that by default the entity.id field is set to UUID()

However, if your PostgreSQL instance isn't setup you will not be able to insert new records.
CREATE EXTENSION 'uuid-ossp'; needs to be enabled on the database.

Also to override the entity.id field please note that you have to call entity.id$

**Comment by mirceaalexandru** [comment]
@combsco 

That library is used to enable to generate uuid on postgres server. However in our case seneca-postgres-store is generating the id internally as uuid, so this library is not necessary.

The note was added.

I think we can close this, if it is OK with you.
Thank you
